name:                figures
version:             0.1.0.0
github:              "hillliam/salesfigures"
license:             BSD3
author:              "liam hill"
maintainer:          "example@example.com"
copyright:           "2018 liam hill"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            application to display figures from collected data
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/hillliam/salesfigures#readme>

dependencies:
- sqlite-simple     # the database framework i have chosen to use
#- HDBC              # a better database framework
#- HDBC-sqlite3      # for sqlite support
#- persistent-sqlite # for in memory database
#- esqueleto         # for easy table declaration
- pathwalk          # for handaling the full data
- blaze-html        # for generating html
- Spock >= 0.11     # web server
#- plugins          # for executing haskell at runtime
- mtl
- text
- time
- hashmap           # optimized map if used
- lens >= 4.15      # easier object handaling
- base >= 4.7

library:
  source-dirs: src

executables:
  figures-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - figures

tests:
  figures-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HTF        # allows both QuickCheck and HUnit to be used together
    - HUnit      # testing framework i am more likely to use
    - QuickCheck # testing framework
    - hspec      # base testing framework
    - figures
